version: '3.8'

services:
  backend:
    build:
      context: ./code-be
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: binary-tree-project
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./code-be:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

  frontend:
    build:
      context: ./code-fe
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./code-fe:/app
      - /app/node_modules

  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: binary-tree-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local